import{a as S,S as R,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const $="52384777-c1c022b2fee3dc7bb99322d83",q=S.create({baseURL:"https://pixabay.com/api/",params:{key:$,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});async function m(i,t=1){try{const{data:o}=await q.get("",{params:{q:i,page:t}});return o}catch(o){throw o}}const g=document.querySelector(".gallery"),u=document.getElementById("loader"),y=document.querySelector(".btn__load"),x=new R(".gallery a",{captionsData:"alt",captionDelay:250});function _(i){const t=i.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:l,comments:w,downloads:B})=>`
      <li class="card">
        <a href="${s}">
          <img class="card__img" src="${o}" alt="${e}" loading="lazy" />
        </a>
        <div class="card__meta">
          <div><p class="cart__title">Likes</p><p class="cart__text">${r}</p></div>
          <div><p class="cart__title">Views</p><p class="cart__text">${l}</p></div>
          <div><p class="cart__title">Comments</p><p class="cart__text">${w}</p></div>
          <div><p class="cart__title">Downloads</p><p class="cart__text">${B}</p></div>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),x.refresh()}function E(){g.innerHTML=""}function v(){u.classList.add("is-active"),u.setAttribute("aria-busy","true")}function b(){u.classList.remove("is-active"),u.setAttribute("aria-busy","false")}function f(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}const L=document.getElementById("search-form"),M=L.elements["search-text"],P=document.querySelector(".btn__load");let h="",p=1,d=0,n=0;c();L.addEventListener("submit",A);P.addEventListener("click",I);async function A(i){var o;i.preventDefault();const t=M.value.trim();if(!t){a.info({title:"Увага",message:"Введи слово для пошуку.",position:"topRight"});return}h=t,p=1,d=0,n=0,c(),E(),v();try{const s=await m(h,p),{hits:e=[],totalHits:r=0}=s||{};if(d=r,!e.length){a.warning({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}_(e),n+=e.length,a.success({title:"Готово",message:`Знайдено ${d} зображень (показано ${n}).`,position:"topRight",timeout:1800}),n<d?f():(c(),a.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){console.error(s);const e=((o=s==null?void 0:s.response)==null?void 0:o.status)===400?"Некоректний запит до API.":"Сталася помилка під час завантаження. Спробуй пізніше.";a.error({title:"Помилка",message:e,position:"topRight"})}finally{b()}}async function I(){var i;p+=1,v(),c();try{const t=await m(h,p),{hits:o=[]}=t||{};if(!o.length){a.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c();return}const s=document.querySelector(".gallery .card:last-child");_(o),n+=o.length,C(s),n>=d?(c(),a.info({title:"Кінець колекції",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):f()}catch(t){console.error(t);const o=((i=t==null?void 0:t.response)==null?void 0:i.status)===400?"Некоректний запит до API.":"Сталася помилка під час завантаження. Спробуй пізніше.";a.error({title:"Помилка",message:o,position:"topRight"}),f()}finally{b()}}function C(i){const t=document.querySelector(".gallery .card");if(!t)return;const s=(i&&i.getBoundingClientRect()||t.getBoundingClientRect()).height*2;window.scrollBy({top:s,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
