import{a as m,S as f,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const g="52384777-c1c022b2fee3dc7bb99322d83",y=m.create({baseURL:"https://pixabay.com/api/",params:{key:g,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}});function h(i){return y.get("",{params:{q:i}}).then(r=>r.data)}const l=document.querySelector(".gallery"),c=document.getElementById("loader"),_=new f(".gallery a",{captionsData:"alt",captionDelay:250});function v(i){const r=i.map(({webformatURL:t,largeImageURL:a,tags:e,likes:s,views:o,comments:p,downloads:d})=>`
      <li class="card">
        <a href="${a}">
          <img class="card__img" src="${t}" alt="${e}" loading="lazy" />
        </a>
        <div class="card__meta">
          <div><p class="cart__title">Likes</p><p class="cart__text">${s}</p></div>
          <div><p class="cart__title">Views</p><p class="cart__text">${o}</p></div>
          <div><p class="cart__title">Comments</p><p class="cart__text">${p}</p></div>
          <div><p class="cart__title">Downloads</p><p class="cart__text">${d}</p></div>
        </div>
      </li>`).join("");l.insertAdjacentHTML("beforeend",r),_.refresh()}function b(){l.innerHTML=""}function L(){c.classList.add("is-active"),c.setAttribute("aria-busy","true")}function x(){c.classList.remove("is-active"),c.setAttribute("aria-busy","false")}const u=document.getElementById("search-form"),$=u.elements["search-text"];u.addEventListener("submit",E);function E(i){i.preventDefault();const r=$.value.trim();if(!r){n.info({title:"Увага",message:"Введи слово для пошуку.",position:"topRight"});return}b(),L(),h(r).then(({hits:t,totalHits:a})=>{if(!t||t.length===0){n.warning({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(t),n.success({title:"Готово",message:`Знайдено ${a} зображень (показано ${t.length}).`,position:"topRight",timeout:1800})}).catch(t=>{var e;console.error(t);const a=((e=t==null?void 0:t.response)==null?void 0:e.status)===400?"Некоректний запит до API.":"Сталася помилка під час завантаження. Спробуй пізніше.";n.error({title:"Помилка",message:a,position:"topRight"})}).finally(()=>{x()})}
//# sourceMappingURL=index.js.map
